[profile.default]
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
cache_path  = 'forge-cache'
solc_version = '0.8.23'
evm_version = 'paris'
via_ir = true
optimizer = true
optimizer_runs = 200
fork_url = "https://base-sepolia.g.alchemy.com/v2/7Ru5qKEuujjl7rQxQytdiKiYrrDeBMcM"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
spotlightSepolia = "${HTTP_RPC_URL_SPOTLIGHT_SEPOLIA}"
spotlight = "${HTTP_RPC_URL_SPOTLIGHT_MAINNET}"
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/7Ru5qKEuujjl7rQxQytdiKiYrrDeBMcM"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
spotlightSepolia = { key = "${SPOTLIGHT_SEPOLIA_BASE_SCAN_API_KEY}", url = "https://spotlight-sepolia.explorer.alchemy.com/api" }
spotlight = { key = "${SPOTLIGHT_MAINNET_BASE_SCAN_API_KEY}", url = "https://spotlight-mainnet.explorer.alchemy.com/api" }

# Chain Configurations
[profile.chains]
spotlightSepolia = { chain_id = 10058112, block_explorer_url = "https://spotlight-sepolia.explorer.alchemy.com/" }
spotlight = { chain_id = 10058111, block_explorer_url = "https://spotlight-mainnet.explorer.alchemy.com/" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
